# Generated by Django 3.2.4 on 2021-06-30 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesreport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Mobile_num',
            field=models.CharField(max_length=10),
        ),
    ]
